export const queryKeys = {
  loginDev: "login-token",
  commonCodeList: "common-code-list",
  updatedChildInfo: "selected-child-info",
  childrenList: "children-list",
  coachingList: "coaching-list",
  selectedCoacingInfo: "selected-coaching-info",
  classList: "class-list",
  selectedClassInfo: "selected-class-info",
  checkValidCoachingToApply: "check-valid-coaching-to-apply",
  appliedCoachingList: "applied-coaching-list",
  appliedCoachingInfo: "applied-coaching-info",
  purchaseCoaching: "purchase-coaching",
  purchaseClasses: "purchase-classes",
  alarmConfig: "alarm-config",
  noticeList: "notice-list",
  noticeDetail: "notice-detail",
  surveyQuestionList: "survey-question-list",
  selectedTaskInfo: "selected-task-info",
  surveyAnswerList: "survey-answer-list",
  videoAssignmentResult: "video-assignment-result",
  userInfo: "user-info",
};

export const mutationKeys = {};
