name: Monitor - b/feature(fix) a/Build

on:
  push:
    branches: [feature/**, fix/**]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - run: cp env/dev.env .env

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Send slack message
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     author_name: Deploy Develop
      #     fields: repo,message,commit,author,workflow,took
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: always()
